### ISSUE TITLE
Email Scrapping

### ISSUE THREAD

**Issue by saranvarma** [dcondrey/scrapy-spiders#1]
HI ,
I want to scrape emails of particular domain in web . Like if i give some domain eg:www.xyz.com , it should fetch emails of that domain like abc@xyz.com , efg@xyz.com  . can you please guide me which script is suitable for me ? Iam new to phython

**Comment by nikparmar** [comment]
Is this even possible? Do your research properly

**Comment by saranvarma** [comment]
see emailhunter.co . how he is doing that ?

**Comment by nikparmar** [comment]
It is clearly indexing all the web pages like a search engine and finding email addresses on it and mapping them to a domain

**Comment by saranvarma** [comment]
Any suggestions to do that ?

**Comment by nikparmar** [comment]
It can be achieved by crawling all the websites like making a search engine kind of thing using Solr and Nutch. Storing the data finding all the email-id and mapping them to the domain name.

You can go for finding a open source search engine also and make it use according to your needs.

**Comment by saranvarma** [comment]
Ok . Thank you bro , iam trying to use bing

**Comment by nikparmar** [comment]
Hey @saranvarma can you close this issue. And can contact me directly here - nkp992@gmail.com

**Comment by saranvarma** [comment]
Ok bro . Thank you
